apiVersion: batch/v1
kind: Job
metadata:
  name: dq-init-job
spec:
  template:
    spec:
      containers:
      - name: init-s3
        image: dq-runner:latest
        imagePullPolicy: Never
        command: ["python", "/app/scripts/init_storage.py"]
        env:
        - name: S3_ENDPOINT
          value: "http://minio:9000"
        - name: PYTHONPATH
          value: "/app"
        volumeMounts:
        - name: code-volume
          mountPath: "/app"
      volumes:
      - name: code-volume
        hostPath:
          path: "/Users/amohiuddeen/Github/dq-framework-poc"
      restartPolicy: OnFailure
  backoffLimit: 4

